services:
  postgres:
    image: postgres:16.6
    container_name: postgres_prod
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data  
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend

  fast-api:
    container_name: fast_api_bakery
    build:
      context: .
      target: prod
    depends_on:
      - postgres
    restart: unless-stopped
    entrypoint: ["python", "-m", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "4200"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/welcome"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - backend

  # postgres_backup_service:
  #   - container_name: pg_backup
  #   - host: pg_backup 
  #   - image:
      


networks:
  backend:
    driver: bridge  
  frontend:
   driver: bridge  

volumes:
  pg_data:
