services:
  streamlit-test:
    container_name: bakery-avenida-test
    image: oseliocandido/bakery-system:test
    environment:
      - DATABASE_STREAMLIT_PATH=/app/data/test_data.db
    ports:
      - "8502:8502"
    volumes:
      - ./logs/:/app/logs/
      - ./app/src/:/app/src/
      - ./data/data.db.example:/app/data/test_data.db
      - ${HOME}/secrets/:/app/src/.streamlit/
  